name: 'data_vault_demo'
version: '1.0.0'
config-version: 2

profile: 'data_vault_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"
models:
  data_vault_demo:
    raw_stg:
      +schema: staging
      +materialized: view
