version: 2

sources:
  - name: dvdrental
    database: dvdrental
    schema: raw_data
    tables:
      - name: actor
        columns:
          - name: actor_id
            tests:
              - unique
              - not_null
      - name: address
        columns:
          - name: address_id
            tests:
              - unique
              - not_null
      - name: category
        columns:
          - name: category_id
            tests:
              - unique
              - not_null
      - name: city
        columns:
          - name: city_id
            tests:
              - unique
              - not_null
      - name: country
        columns:
          - name: country_id
            tests:
              - unique
              - not_null
      - name: customer
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
      - name: film
        columns:
          - name: film_id
            tests:
              - unique
              - not_null
      - name: film_actor
        columns:
          - name: film_id
            tests:
              - relationships:
                  to: source('dvdrental', 'film')
                  field: film_id
          - name: actor_id
            tests:
              - relationships:
                  to: source('dvdrental', 'actor')
                  field: actor_id
      - name: film_category
        columns:
          - name: film_id
            tests:
              - relationships:
                  to: source('dvdrental', 'film')
                  field: film_id
          - name: category_id
            tests:
              - relationships:
                  to: source('dvdrental', 'category')
                  field: category_id
      - name: inventory
        columns:
          - name: inventory_id
            tests:
              - unique
              - not_null
      - name: language
        columns:
          - name: language_id
            tests:
              - unique
              - not_null
      - name: payment
        columns:
          - name: payment_id
            tests:
              - unique
              - not_null
      - name: rental
        columns:
          - name: rental_id
            tests:
              - unique
              - not_null
      - name: staff
        columns:
          - name: staff_id
            tests:
              - unique
              - not_null
      - name: store
        columns:
          - name: store_id
            tests:
              - unique
              - not_null

